name: Basic Branch Check

# Trigger this action every single time code is pushed anywhere
on:
  push:

        branches:
          - '**'          # This matches every branch (including your feature branch)
  pull_request:
    branches:
      - main          # Triggers when someone tries to merge into main


jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      # Prints the exact name of the branch you just pushed to
      - name: Show my branch name
        run: echo "Hello! You just pushed code to the branch named -> ${{ github.ref_name }}"